# Generated by Django 6.0.2 on 2026-08-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeck',
            name='format',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('commander', 'Commander')], max_length=100, null=True),
        ),
    ]
