# Generated by Django 6.0.2 on 2026-03-10 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ColorIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManaCostColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SetId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SetName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.CharField(blank=True, max_length=100, null=True)),
                ('oracle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image_uri', models.URLField(blank=True, null=True)),
                ('mana_cost_numeric', models.PositiveIntegerField(blank=True, null=True)),
                ('cmc', models.FloatField(blank=True, null=True)),
                ('oracle_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('standard_legal', models.BooleanField(blank=True, null=True)),
                ('commander_legal', models.BooleanField(blank=True, null=True)),
                ('colors', models.ManyToManyField(blank=True, related_name='cards', to='card_search.color')),
                ('color_identity', models.ManyToManyField(blank=True, related_name='cards', to='card_search.coloridentity')),
                ('keywords', models.ManyToManyField(blank=True, related_name='cards', to='card_search.keywords')),
                ('mana_cost_color', models.ManyToManyField(blank=True, null=True, related_name='cards', to='card_search.manacostcolor')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.name')),
                ('rarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.rarity')),
                ('released_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.releasedat')),
                ('set_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.setcode')),
                ('set_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.setid')),
                ('set_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card_search.setname')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card_search.type')),
            ],
        ),
    ]
